# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: befe2c01afc8e1e7f8b73357cb0207538e78a6450c96d992de02d8122a9cf4431b5391bc9e9a7cc93a0e40c69a5359213069e1bcbd2f8b8ae1765256fde5f255

test:
  secret_key_base: b7f779281a031f0593d540f397d6da82f3e6161cf3b3d18e09bdac2d71d74334e479ac3ba14c8e04e78fc1c6c66c4d7b328559cb1901d899dc1ea86753dad0b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
